public class MPActorWrapper {

//    public Boolean adult;
//    public String imdb_id;
//    public String homepage;
//    public Integer gender;
//    public Double popularity;
    @AuraEnabled public Date birthday;
    @AuraEnabled public String known_for_department;
    @AuraEnabled public Date deathday;
    @AuraEnabled public String id;
    @AuraEnabled public String name;
    @AuraEnabled public List<String> also_known_as;
    @AuraEnabled public String biography;
    @AuraEnabled public String place_of_birth;
    @AuraEnabled public String profile_path;
}